# Mythical Mane domain models, generated by `python manage.py inspectdb` and
# then trimmed to remove Django's own internal tables (auth_*, django_*),
# which are already defined by django.contrib.auth, django.contrib.admin,
# django.contrib.contenttypes, and django.contrib.sessions.
#
# Every model below uses `managed = False` because the underlying tables were
# created by `mm-schema.sql` in Supabase, NOT by Django migrations. Do not flip
# any of these to `managed = True` — Django would then try to create or alter
# tables that already exist.
from django.db import models


class Ability(models.Model):
    ability_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    ability_type = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ability'

    def __str__(self):
        return self.name


class Diagnosis(models.Model):
    diagnosis_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    code = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'diagnosis'
        verbose_name_plural = 'Diagnoses'

    def __str__(self):
        return self.name


class Employee(models.Model):
    employee_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    job_role = models.TextField()
    specialty = models.TextField(blank=True, null=True)
    hire_date = models.DateField()
    phone = models.TextField()
    email = models.TextField()
    schedule = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'employee'

    def __str__(self):
        return f"{self.name} ({self.job_role})"


class Invoice(models.Model):
    invoice_id = models.BigAutoField(primary_key=True)
    visit = models.ForeignKey('Visit', models.DO_NOTHING)
    status = models.TextField()
    due_date = models.DateField(blank=True, null=True)
    issue_date = models.DateField()

    class Meta:
        managed = False
        db_table = 'invoice'


class LineItem(models.Model):
    line_item_id = models.BigAutoField(primary_key=True)
    invoice = models.ForeignKey(Invoice, models.DO_NOTHING)
    line_item_type = models.TextField()
    visit_procedure = models.ForeignKey('VisitProcedure', models.DO_NOTHING, blank=True, null=True)
    medication_id = models.BigIntegerField(blank=True, null=True)
    vaccination_id = models.BigIntegerField(blank=True, null=True)
    boarding_stay_id = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'line_item'


class Observation(models.Model):
    observation_id = models.BigAutoField(primary_key=True)
    visit_procedure = models.ForeignKey('VisitProcedure', models.DO_NOTHING)
    observation_type = models.TextField(blank=True, null=True)
    observed_value = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    unit = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'observation'


class Universe(models.Model):
    universe_id = models.BigAutoField(primary_key=True)
    name = models.TextField()

    class Meta:
        managed = False
        db_table = 'universe'

    def __str__(self):
        return self.name


class Owner(models.Model):
    owner_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    phone = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    universe = models.ForeignKey(Universe, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'owner'

    def __str__(self):
        return self.name


class Patient(models.Model):
    patient_id = models.BigAutoField(primary_key=True)
    dob = models.DateField(blank=True, null=True)
    name = models.TextField()
    color = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(Owner, models.DO_NOTHING)
    species_id = models.BigIntegerField(blank=True, null=True)
    breed_id = models.BigIntegerField(blank=True, null=True)
    universe = models.ForeignKey(Universe, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'patient'

    def __str__(self):
        return self.name


class PatientAbility(models.Model):
    patient_ability_id = models.BigAutoField(primary_key=True)
    patient = models.ForeignKey(Patient, models.DO_NOTHING)
    ability = models.ForeignKey(Ability, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'patient_ability'
        unique_together = (('patient', 'ability'),)
        verbose_name_plural = 'Patient abilities'


class Payment(models.Model):
    payment_id = models.BigAutoField(primary_key=True)
    invoice = models.ForeignKey(Invoice, models.DO_NOTHING)
    payment_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.TextField()

    class Meta:
        managed = False
        db_table = 'payment'


class ProcedureDefinition(models.Model):
    procedure_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    standard_cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'procedure_definition'

    def __str__(self):
        return self.name


class Visit(models.Model):
    visit_id = models.BigAutoField(primary_key=True)
    patient = models.ForeignKey(Patient, models.DO_NOTHING)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField(blank=True, null=True)
    reason = models.TextField(blank=True, null=True)
    vet = models.ForeignKey(Employee, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'visit'

    def __str__(self):
        return f"Visit #{self.visit_id} — {self.patient_id} on {self.start_at:%Y-%m-%d}"


class VisitDiagnosis(models.Model):
    visit_diagnosis_id = models.BigAutoField(primary_key=True)
    visit = models.ForeignKey(Visit, models.DO_NOTHING)
    diagnosis = models.ForeignKey(Diagnosis, models.DO_NOTHING)
    employee = models.ForeignKey(Employee, models.DO_NOTHING, blank=True, null=True)
    recorded_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'visit_diagnosis'
        unique_together = (('visit', 'diagnosis', 'recorded_at'),)
        verbose_name_plural = 'Visit diagnoses'


class VisitProcedure(models.Model):
    visit_procedure_id = models.BigAutoField(primary_key=True)
    visit = models.ForeignKey(Visit, models.DO_NOTHING)
    procedure = models.ForeignKey(ProcedureDefinition, models.DO_NOTHING)
    employee = models.ForeignKey(Employee, models.DO_NOTHING, blank=True, null=True)
    performed_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'visit_procedure'
        unique_together = (('visit', 'procedure', 'performed_at'),)


# ---------------------------------------------------------------------------
# Django-OWNED model (Mission 7).
#
# Unlike everything above, this model is NOT marked managed = False — Django
# DOES own this table. `python manage.py makemigrations` followed by
# `python manage.py migrate` will create the underlying `care_note` table in
# Supabase, demonstrating that we can mix legacy/unmanaged tables and
# Django-owned tables in the same database.
# ---------------------------------------------------------------------------

class CareNote(models.Model):
    """A free-form clinical note attached to a patient.

    This is a Django-managed table (created by migration 0001_initial). It links
    to the unmanaged Patient model, which is fine — Django will create the FK
    constraint pointing at patient.patient_id when the migration runs.
    """
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        related_name="care_notes",
    )
    note = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    follow_up_date = models.DateField(
        blank=True,
        null=True,
        help_text="Optional date by which someone should follow up.",
    )
    resolved = models.BooleanField(default=False)

    class Meta:
        db_table = "care_note"
        ordering = ("-created_at",)
        verbose_name = "Care note"
        verbose_name_plural = "Care notes"

    def __str__(self):
        marker = "[resolved] " if self.resolved else ""
        snippet = (self.note[:60] + "...") if len(self.note) > 60 else self.note
        return f"{marker}{self.patient.name}: {snippet}"
